language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-20mode
  - jruby-21mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
