sudo: required
dist: trusty
language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.4
  - 2.3.1
  - ruby-head
env:
  - TEST_TASK=spec
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
  include:
    - rvm: 2.3.1
      env: TEST_TASK=rubocop
    - rvm: jruby-9.0.5.0
      env: JRUBY_OPTS='-J-Xmx256M'
    - rvm: jruby-head
      env: JRUBY_OPTS='-J-Xmx256M'
  fail_fast: true
addons:
  apt:
    packages:
      - libgmp-dev
script: bundle exec rake $TEST_TASK
